spring:
  profiles:
    active: dev0
  application:
    name: eureka-server
server:
  port: 8759
eureka:
  client:
    fetch-registry: false

---
#服务配置
spring:
  profiles: dev0
eureka:
  instance:
    #prefer-ip-address: true
    hostname: peer0
  client:
    #register-with-eureka: false
    #fetch-registry: false
    service-url:
      defaultZone: http://peer2:8757/eureka/,http://peer1:8758/eureka/
