spring:
  profiles:
    active: dev2
  application:
    name: eureka-server
server:
  port: 8757
eureka:
  client:
    fetch-registry: false

---
#服务配置
spring:
  profiles: dev2
eureka:
  instance:
    #prefer-ip-address: true
    hostname: peer2
  client:
    #register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer1:8758/eureka/,http://peer0:8759/eureka/