spring:
  application:
    name: consumer-service
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8757/eureka/,http://peer1:8758/eureka/,http://peer0:8759/eureka/